# Generated by Django 4.2.5 on 2023-10-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_orderlist_product_delete_shoppinglist"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
