# Generated by Django 4.2.5 on 2023-10-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_product_product_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_sale",
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
