# Generated by Django 4.2.5 on 2023-10-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_product_product_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_sale",
            field=models.IntegerField(max_length=12),
        ),
    ]
