# Generated by Django 4.2.5 on 2023-10-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_product_product_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_sale",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
