# Generated by Django 4.2.5 on 2023-11-10 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_albummodel_photomodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pname", models.CharField(default="", max_length=100)),
                ("unitprice", models.IntegerField(default=0)),
                ("quantity", models.IntegerField(default=0)),
                ("dtotal", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="OrdersModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtotal", models.IntegerField(default=0)),
                ("shipping", models.IntegerField(default=0)),
                ("grandtotal", models.IntegerField(default=0)),
                ("customname", models.CharField(default="", max_length=100)),
                ("customemail", models.CharField(default="", max_length=100)),
                ("customaddress", models.CharField(default="", max_length=100)),
                ("customphone", models.CharField(default="", max_length=100)),
                ("paytype", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Orderlist",
        ),
        migrations.AddField(
            model_name="product",
            name="product_storage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="detailmodel",
            name="dorder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.ordersmodel"
            ),
        ),
    ]
